app/weather_reminder/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path

from core import views as core_views
from setups import views as setups_views

from .views import HelloApiView, HelloTemplateView, ping

auth_urlpatterns = (
    [
        path("signup/", core_views.SignUpView.as_view(), name="signup"),
        path("login/", core_views.LoginView.as_view(), name="login"),
        path("logout/", auth_views.LogoutView.as_view(), name="logout"),
        re_path(
            r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$",
            core_views.ConfirmEmailView.as_view(),
            name="activate",
        ),
    ],
    "auth",
)


user_urlpatterns = (
    [
        path("create/", core_views.CreateUserView.as_view(), name="create"),
        path("me/", core_views.ManageUserView.as_view(), name="me"),
        path("forecast/", core_views.UserForecastListApiView.as_view(), name="my_forecast_api"),
        re_path(r"^forecast/(?P<city_name>[\w\s]+)/$",
                core_views.UserForecastAPIView.as_view(), name="user_forecast_api"),
    ],
    "user",
)

setups_urlpatterns = (
    [
        re_path(r"^(?P<hour>[0-9]{1,2})/$", setups_views.SetupApiView.as_view(), name="create"),
        path("exists/", setups_views.SubscriptionExistsApiView.as_view(), name="setup_exists")
    ],
    "setups",
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ping/", ping, name="ping"),
    path("api/hello/", HelloApiView.as_view(), name="api-hello"),
    path("hello/", HelloTemplateView.as_view(), name="hello"),
    path("", core_views.HomeView.as_view(), name="home"),
    path("forecast/", core_views.ForecastView.as_view(), name="forecast"),
    path("auth/", include(auth_urlpatterns)),
    path("api/user/", include(user_urlpatterns)),
    path("api/setups/", include(setups_urlpatterns)),
    path(
        "api/token/",
        core_views.MyTokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/token/refresh/",
        core_views.MyTokenRefreshView.as_view(),
        name="token_refresh",
    ),
]

app/core/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user"""
        if not email:
            raise ValueError("User must have an email address")
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.is_active = False
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports using email instead of username"""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"


class City(models.Model):
    """City object"""

    name = models.CharField(max_length=255, unique=True)
    forecast = models.JSONField(default=list, blank=True, null=True)
    members = models.ManyToManyField(User, through="UserForecast")
    lat = models.DecimalField(max_digits=6, decimal_places=4, blank=True, null=True)
    long = models.DecimalField(max_digits=7, decimal_places=4, blank=True, null=True)

    def __str__(self):
        return self.name


class UserForecast(models.Model):
    """User Weather Forecast M2M object"""

    city = models.ForeignKey(City, related_name="cities", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="users", on_delete=models.CASCADE)

    def __str__(self):
        return f"City: {self.city.name}, User:{self.user.id}"

    class Meta:
        unique_together = ("city", "user")

app/core/forms.py
from django import forms


class SignUpForm(forms.Form):

    email = forms.CharField(max_length=255)
    name = forms.CharField(max_length=255)
    password1 = forms.CharField(max_length=50)
    password2 = forms.CharField(max_length=50)

app/core/views.py
from datetime import datetime

from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render, reverse
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework_simplejwt import authentication
from rest_framework_simplejwt.exceptions import InvalidToken, TokenError
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


from .models import City, UserForecast
from .serializers import (
    MyTokenObtainPairSerializer,
    UserForecastListSerializer,
    UserForecastSerializer,
    UserSerializer,
)
from .utils.email_confirmation import account_activation_token


class CreateUserView(generics.CreateAPIView):
    """Create a new user in the system"""

    serializer_class = UserSerializer

    @classmethod
    def as_view(cls, **initkwargs):
        # Force enables CSRF protection.  This is needed for unauthenticated API endpoints
        # because DjangoRestFramework relies on SessionAuthentication for CSRF validation
        view = super().as_view(**initkwargs)
        view.csrf_exempt = False
        return view


class ManageUserView(generics.RetrieveUpdateAPIView):
    """Manage the authenticated user"""

    serializer_class = UserSerializer
    authentication_classes = (authentication.JWTAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get_object(self):
        return self.request.user


class SignUpView(FormView):
    template_name = "core/signup.html"
    form_class = forms.Form


class LoginView(FormView):
    template_name = "core/login.html"
    form_class = forms.Form


class ConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = get_user_model().objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect(reverse("auth:login"))
        else:
            return render(request, "auth/account_activation_invalid.html")


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])
        data = {
            "accessToken": serializer.validated_data["access"],
            "tokenExpire": settings.SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"].total_seconds(),
        }
        response = JsonResponse(data)
        response.set_cookie(
            "refresh-token",
            value=serializer.validated_data["refresh"],
            httponly=True,
            samesite="Lax",
            expires=datetime.utcnow() + settings.SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"],
        )

        return response


class MyTokenRefreshView(TokenRefreshView):
    def post(self, request, *args, **kwargs):
        data = {"refresh": request.COOKIES["refresh-token"]}
        serializer = self.get_serializer(data=data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])
        response_data = {
            "accessToken": serializer.validated_data["access"],
            "tokenExpire": settings.SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"].total_seconds(),
        }

        return Response(response_data, status=status.HTTP_200_OK)


class HomeView(TemplateView):
    template_name = "core/home.html"


class UserForecastListApiView(generics.ListAPIView):
    """User's forecasts view"""
    serializer_class = UserForecastListSerializer
    permission_classes = [permissions.IsAuthenticated, ]

    def get_queryset(self):
        """
        Returns a list of user's cities with corresponding forecasts
        """
        user = self.request.user
        return UserForecast.objects.filter(user=user)


class UserForecastAPIView(generics.CreateAPIView):
    serializer_class = UserForecastSerializer
    permission_classes = [permissions.IsAuthenticated, ]

    def delete(self, request, city_name, format=None):
        """Deletes a current user's forecast by city name"""
        user = self.request.user
        city = City.objects.get(name=city_name)
        try:
            user_forecast = UserForecast.objects.get(user=user, city=city)
        except UserForecast.DoesNotExist:
            raise Http404("No UserForecast matches the given query.")
        user_forecast.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ForecastView(LoginRequiredMixin, ListView):
    model = UserForecast
    template_name = 'core/forecast.html'

    def get_queryset(self):
        user = self.request.user
        user_cities_names = UserForecast.objects.filter(user=user)\
            .prefetch_related("city")\
            .values_list("city__name", flat=True)
        cities_to_choose_from = City.objects.values_list('name', flat=True)\
            .exclude(name__in=user_cities_names)
        return cities_to_choose_from

app/templates/core/forecast.html
{% extends "main.html" %}
{% load static %}
{% block title %} Forecast {% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="container" id="cities-forecast">
        <div class="d-flex">
            <select class="form-select me-1" id="select-city-to-add" aria-label="Default select example">
			<option selected>Choose a city</option>
			{% if object_list %}
				{% for city_name in object_list %}
				<option id="select-{city_name}" value="{{city_name}}">{{city_name}}</option>
				{% endfor %}
				</select>
			{% endif %}
            <button onclick="addCityToUser()" class="btn btn-primary">Add</button>
        </div>
    </div>
</div>
<input type="hidden" id="userForecastUrl" forecast-url="{% url 'user:my_forecast_api'%}"/>
<script>
  const userForecastUrl = document
  .querySelector('#userForecastUrl')
  .getAttribute('forecast-url');
</script>

<script type="text/javascript" src={% static "js/checkAuth.js" %}></script>
<script type="text/javascript" src={% static "js/myForecast.js" %}></script>
<script>getUserWeather(userForecastUrl)</script>
<script>
const addCityToUser = () => {
	const cityName = document.querySelector('#select-city-to-add').value;
	if (cityName === "Choose a city") {
		return false;
	};
	authHttpClient(`/api/user/forecast/${cityName}/`, 'post').then(
		(response) => {
			forecastDiv = document.querySelector('#cities-forecast');
			forecastDiv.insertAdjacentHTML(
				'beforeend',
				`<div id="${(cityName).replace(/\s/g, '')}-div" class="mt-3">
					<h4>
						${cityName}  
						<button type="button" 
						onclick="removeCityFromUser('${cityName}')" 
						class="btn btn-outline-danger btn-sm float-end">Remove
						</button>
					</h4>
					<div class="card-group mt-2" id="forecast-${(cityName).replace(/\s/g, '')}">
					</div>
				</div>`);
			var select = document.querySelector('#select-city-to-add');
			select.selectedIndex = 0;
			select.removeChild(select.querySelector(`option[value="${cityName}"]`));
			;
			addFourDaysDailyWeatherCards(
				cityName,
				response.data.city.forecast.daily
			);
		},
		(error) => {
			const errors = error.response.data;
			console.log(errors);
		}
	);
};
const removeCityFromUser = (cityName) => {
	authHttpClient(`/api/user/forecast/${cityName}/`, "delete").then(
		(response) => {
			let elem = document.querySelector(`#${cityName.replace(/\s/g, '')}-div`); 
			elem.parentNode.removeChild(elem);
			let select = document.querySelector('#select-city-to-add');
			select.insertAdjacentHTML(
			'beforeend',
			`<option id="select-${cityName}" value="${cityName}">${cityName}</option>`
			);
		},
		(error) => {
			const errors = error.response.data;
			console.log(errors);
		}
	);
};
</script>

{% endblock content %}

app/templates/core/home.html
{% extends "main.html" %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block content %}
<div class="container-fluid">
    <div class="container">
        <p>User : {{ user.email }}</p>
        <p>Is authenticated? {{ user.is_authenticated }}</p> 
    </div>
    {% if user.is_authenticated %}
        <div class="container" id="subscription-div">
            <p id="message">Daily weather updates at your email</p>
        </div>
    {% endif %}
</div>
<script type="text/javascript" src={% static "js/checkAuth.js" %}></script>
<script type="text/javascript" src={% static "js/setups/checkSubscription.js" %}></script>
<script>
    const getSubscriptionData = () => {
        authHttpClient('/api/setups/exists/', "get").then(
            (response) => {
                return renderSubscriptionData(response.data);
            },
            (error) => {
                console.log(error.response.data);
            }
        ).then(

        )
    };
    const removeSubscription = (time) => {
        authHttpClient(`/api/setups/${time}/`, "delete").then(
            (response) => {
                renderSubscriptionData({"exists": false});
            },
            (error) => {
                console.log(error.response.data);
            }
        );
    };
    const subscribeForWeatherUpdates = () => {
        const time = document.querySelector('#select-hour').value;
        authHttpClient(`/api/setups/${time}/`, "post").then(
            (response) => {
                renderSubscriptionData(getSubscriptionData());
            },
            (error) => {
                console.log(error.response.data);
            }
        );
    };
    getSubscriptionData();
</script>
{% endblock content %}

app/templates/core/login.html
{% extends "main.html" %}
{% load static %}
{% block javascript %}
<script type="text/javascript" src={% static "js/core/login.js" %}></script>
<!-- <script type="text/javascript" src={% static "js/inMemoryJwt.js" %}></script> -->
{% endblock %}
{% block content %}
<div>
    <h2> Login</h2>
    <p style="color: red;" id="err"></p>
    <p><label for="id_email">Email:</label> <input type="text" name="email" maxlength="255" required id="id_email"></p>
    <p><label for="id_password">Password:</label> <input type="password" name="password" required id="id_password"></p>
    <button onclick="authUser()">Submit</button>
    <input type="hidden" id="homeUrl" home-url="{% url 'home'%}" />

    <script>
        const urlParams = new URLSearchParams(window.location.search);
        const afterSignup = urlParams.has('after-signup');
        if (afterSignup) {
            const loginHeading = document.querySelector('h2');
            const message = document.createElement('p');
            message.innerHTML = "The confirmation link was sent to your email address.";
            loginHeading.parentNode.insertBefore(message, loginHeading);
        }
    </script>
</div>
{% endblock %}

app/templates/core/signup.html
{% extends "main.html" %}
{% load static %}
{% block javascript %}
<!-- <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script> -->
<script type="text/javascript" src={% static "js/core/signup.js" %}></script>
{% endblock %}
{% block content %}

<div class="container-fluid">
    
    <div class="container" id="cities-forecast">
        {% csrf_token %}
        <h2> Sign Up</h2>
        <div class="mb-3">
            <p style="color: red;" id="email_err"></p>
            <label for="id_email" class="form-label">Email address</label>
            <input type="text" class="form-control" id="id_email" name="email" maxlength="255" required aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
            <p style="color: red;" id="name_err"></p>
            <label class="form-label" for="id_name">Name</label> 
            <input type="text"class="form-control" name="name" maxlength="255" required id="id_name">
        </div>
        <div class="mb-3">
            <label class="form-label" for="id_password1">Password</label> 
            <input class="form-control" type="password" name="password1" required id="id_password1">
            <p style="color: red;" id="password_err"></p>
        </div>
        <div class="mb-3">
            <label class="form-label" for="id_password2">Password confirmation</label> 
            <input class="form-control" type="password" name="password2" required id="id_password2">
        </div>
        <button onclick="createUser()" class="btn btn-primary">Submit</button>
    </div>
    <input type="hidden" id="loginUrl" login-url="{% url 'auth:login'%}?after-signup=true"/>
</div>
{% endblock %}